export const personalAssistance = async(req, res) => {
    try {
        
    } catch (error) {
        
    }
}